// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

using khs.interval.model;

namespace khs.interval
{
	public partial class StartViewController : UIViewController
	{
		private Interval Domain { get; set; }
		private IntervalDetailViewController ParentController { get; set; }

		public StartViewController (IntPtr handle) : base (handle)
		{
		}

		public void SetInterval (IntervalDetailViewController controller, Interval interval)
		{
			Domain = interval;
			ParentController = controller;
		}

	}
}
